
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
[1] "2021-07-16"
Error in select(., region, provincia, comuna, codigo_comuna) : 
  object 'provincias_comunas' not found
Calls: %>% ... same_src.data.frame -> is.data.frame -> %>% -> select
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/provincias_comunas.rdata', probable reason 'No such file or directory'
Execution halted
[1] "2021-07-19"
[1] "2021-07-22"
[1] "2021-07-19"
[1] "2021-07-22"
